version: 0.0
os: linux
files:
  - source: flask-master-site
    destination: /home/ubuntu/visitly/
hooks:
  BeforeInstall:
    - location: /scripts/removeoldfiles.sh
  AfterInstall:
    - location: /scripts/startwebserver.sh
    - location: /scripts/unziparchive.sh
